spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.wy.entity
  mapper-locations: classpath:mapper/*.xml

